### ISSUE TITLE
swoole服务连不上

### ISSUE THREAD

**Issue by cowcomic** [gopeak/masterlab-docker#4]
按照说明部署swoole之后
在服务中进行了配置
![image](https://user-images.githubusercontent.com/4745969/115502315-51c47600-a2a7-11eb-9a8f-5b02b0d412e1.png)

但是一直连不上
![image](https://user-images.githubusercontent.com/4745969/115502295-46714a80-a2a7-11eb-8828-1d7b33a319b7.png)

**Comment by zhejiez** [comment]
解决了吗,我也遇到了

**Comment by cowcomic** [comment]
> 解决了吗,我也遇到了

没解决，换产品了
